<?php

use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\my_testimonial\Entity\Testimonial;

/**
 * Implements hook_entity_type_build().
 */
function my_testimonial_entity_type_build(EntityTypeManagerInterface $entity_type_manager) {
  $entity_type = $entity_type_manager->getDefinition('node');
  $entity_type->addBundle('testimonial');
}

/**
 * Implements hook_entity_base_field_info().
 */
function my_testimonial_entity_base_field_info($entity_type) {
  if ($entity_type->id() === 'node') {
    return []; // Field definitions are already defined in the Testimonial class
  }
}
